# Using 2 spaces as indent
defaultIndent: "  "

# Using semantic line break (https://sembr.org/)
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1              # 0/1
    removeSentenceLineBreaks: 0         # 0/1
    multipleSpacesToSingle: 1           # 0/1
    textWrapSentences: 0                # 1 disables main textWrap
    sentenceIndent: ""
    sentencesFollow:
      par: 1                            # 0/1
      blankLine: 1                      # 0/1
      fullStop: 1                       # 0/1
      exclamationMark: 1                # 0/1
      questionMark: 1                   # 0/1
      rightBrace: 1                     # 0/1
      commentOnPreviousLine: 1          # 0/1
      other: 0                          # regex
    sentencesBeginWith:
      A-Z: 1                            # 0/1
      a-z: 0                            # 0/1
      other: 0                          # regex
    sentencesEndWith:
      basicFullStop: 0                  # 0/1
      betterFullStop: 1                 # 0/1
      exclamationMark: 1                # 0/1
      questionMark: 1                   # 0/1
      other: 0                          # regex
    sentencesDoNOTcontain:
      other: |-                          # regex
        (?x)
        \\begin
        |
        \\cmh

fineTuning:
  modifyLineBreaks:
    betterFullStop: |-
      (?x)                                # ignore spaces in the below
      (?:                                 #
        \.\)                              # .)
        (?!\h*[a-z])                      # not *followed by* a-z
      )                                   #
      |                                   # OR
      (?:                                 #
        (?<!                              # not *preceded by*
          (?:                             #
            (?:[eE]\.[gG])                # e.g OR E.g OR e.G OR E.G
            |                             #
            (?:[iI]\.[eE])                # i.e OR I.e OR i.E OR I.E
            |                             #
            (?:etc)                       # etc
            |                             #
            (?:[wW]\.[rR]\.[tT])          # w.r.t OR W.r.t OR w.R.t OR w.r.T OR W.R.t OR W.r.T OR w.R.T OR W.R.T
          )                               #
        )                                 #
      )                                   #
      \.                                  # .
      (?!                                 # not *followed by*
        (?:                               #
          [a-zA-Z0-9-~,]                  #
          |                               #
          \),                             # ),
          |                               #
          \)\.                            # ).
        )                                 #
      )                                   #
